s=[];
w =[1 3 5 10 30 50 100 200 300];
for i=1:9
    L= w(i);
    computerProfit;
    s=[s;pq];
end
l = 40;
X = 1:l;
plot(X,s(1,1:l),'o-r','LineWidth',2,...
    'MarkerEdgeColor','r',...
    'MarkerFaceColor','r','MarkerSize',4);
title('profits with different K');
xlabel('week')
ylabel('profit(%) ')
hold on;
plot(X,s(2,1:l),'o-g','LineWidth',2,...
    'MarkerEdgeColor','g',...
    'MarkerFaceColor','g','MarkerSize',4);
hold on;
plot(X,s(3,1:l),'o-b','LineWidth',2,...
    'MarkerEdgeColor','b',...
    'MarkerFaceColor','b','MarkerSize',4);
hold on;
plot(X,s(4,1:l),'o-c','LineWidth',2,...
    'MarkerEdgeColor','c',...
    'MarkerFaceColor','c','MarkerSize',4);
hold on;
plot(X,s(5,1:l),'o-m','LineWidth',2,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor','m','MarkerSize',4);
hold on
plot(X,s(6,1:l),'o-y','LineWidth',2,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor','y','MarkerSize',4);
hold on
plot(X,s(7,1:l),'o:m','LineWidth',2,...
    'MarkerEdgeColor','m',...
    'MarkerFaceColor','m','MarkerSize',4);
hold on
plot(X,s(8,1:l),'o:y','LineWidth',2,...
    'MarkerEdgeColor','y',...
    'MarkerFaceColor','y','MarkerSize',4);
hold on
plot(X,s(9,1:l),'o-k','LineWidth',2,...
    'MarkerEdgeColor','k',...
    'MarkerFaceColor','k','MarkerSize',4);
hold on
legend('k=1','k=3','k=5','k=10','k=30','k=50','k=100','k=200','k=300');
set(gca,'xtick',[1:1:l],'xlim',[0 l]);
set(gca,'ygrid','on','ylim',[-10 300]);
hold off